### ISSUE TITLE
Input_specs: ~ not working

### ISSUE THREAD

**Issue by koxon** [sportarchive/CloudProcessingEngine-Decider#13]
input_specs: ~ 

is throwing an error. 
Both the workflow input_spec and Activities input_spec need something.

Work around: use:
   type: "object"

**Comment by koxon** [comment]
Fixed ?

**Comment by ceache** [comment]
Should be. See the example that works here https://github.com/sportarchive/CloudTranscode-Decider/blob/master/pydecider/activity.py#L25
