### ISSUE TITLE
Allow custom Activity TaskList

### ISSUE THREAD

**Issue by koxon** [sportarchive/CloudProcessingEngine-Decider#27]
The Decider must allow users to provide the name of the Activity TaskList they want to use for their steps. Generating it automatically is very restrictive and done on the activity level not on the step level.

**Example:**
I want to use the same activity (same version) for two different steps. One step generate thumbnails and I want a dedicated worker for it. The other step generates videos and I provision many workers for it.

I want to make sure the thumbnail worker stays dedicated to the thumbnail generation thus it should listen to a specific TaskList for Thumb jobs only. My videos workers should listen to another TaskList for video jobs only.

The problem today is that the TaskList is generated on the "activity" level. It should be generated on the "step" level. Each step should accept a specific TaskList if provided. This way each step can be processed by a separate activity TaskList.

The only to make this work today, is to have several version of Activities or having several deciders all using different domains.

Within the same domain, you can't segregate activities of same type and version.

**Comment by ceache** [comment]
Hum, you have the same activity name and version for something that does radically different things (video vs thumbnails). Isn't that a departure from SWF recommendations?

You can already select the task_list per activity.
http://sportarchive.github.io/CloudProcessingEngine-Decider/plan_getting_started.html#activities
Couldn't you simply give a different names to your activities? Say ThumbnailActivity vs VideoActivity?

**Comment by koxon** [comment]
It's not radically different. It's a slight change in the FFMpeg command
line.
An activity could have different purposes based on the input it receives.

From your perspective, I should have a unique activity for thumb, video,
audio, image, etc. Not just one generic activity that changes its behavior
based on input ?

On Mon, Jul 27, 2015 at 8:45 AM, Charles-Henri de Boysson <
notifications@github.com> wrote:

> Hum, you have the same activity name and version for something that does
> radically different things (video vs thumbnails). Isn't that a departure
> from SWF recommendations?
> 
> You can already select the task_list per activity.
> 
> http://sportarchive.github.io/CloudProcessingEngine-Decider/plan_getting_started.html#activities
> Couldn't you simply give a different names to your activities? Say
> ThumbnailActivity vs VideoActivity?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sportarchive/CloudProcessingEngine-Decider/issues/27#issuecomment-125192582
> .

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.

**Comment by sportarc** [comment]
Even though I understand your point Ceache, I still think I should be able
to specify my ActivityTask List.

On Mon, Jul 27, 2015 at 9:34 AM, Nicolas Menciere notifications@github.com
wrote:

> It's not radically different. It's a slight change in the FFMpeg command
> line.
> An activity could have different purposes based on the input it receives.
> 
> From your perspective, I should have a unique activity for thumb, video,
> audio, image, etc. Not just one generic activity that changes its behavior
> based on input ?
> 
> On Mon, Jul 27, 2015 at 8:45 AM, Charles-Henri de Boysson <
> notifications@github.com> wrote:
> 
> > Hum, you have the same activity name and version for something that does
> > radically different things (video vs thumbnails). Isn't that a departure
> > from SWF recommendations?
> > 
> > You can already select the task_list per activity.
> > 
> > http://sportarchive.github.io/CloudProcessingEngine-Decider/plan_getting_started.html#activities
> > Couldn't you simply give a different names to your activities? Say
> > ThumbnailActivity vs VideoActivity?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/sportarchive/CloudProcessingEngine-Decider/issues/27#issuecomment-125192582
> > 
> > .
> 
> ## 
> 
> Nicolas Menciere
> Co-Founder and CTO
> Sport Archive Inc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sportarchive/CloudProcessingEngine-Decider/issues/27#issuecomment-125206206
> .

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.
