### ISSUE TITLE
Allow Workflow timeout options in config or plan

### ISSUE THREAD

**Issue by koxon** [sportarchive/CloudProcessingEngine-Decider#28]
Plan needs to handle the options provided by SWF.
Especially the timeout options are they are crucial for scaling and preventing workflow to timeout silently. 

The only way to prevent building a retry logic or a queue logic outside of CPE is to allow workflows to never timeout. If they timeout we are dead in the water.

If they never timeout, we can track the size of the pool and scale at will. For this we must be able to configure SWF workflows when the Decider register them. 
Configuring the activities options would also be a plus but not as critical. However for large transcodes, we will need to control the activities timeout as well.

All those options can be submitted at creation time by the client. This is something I'm looking into, but for simplicity and clarity it makes more sense to have this in the plan. We already have the name and versions. 

thanks

**Comment by ceache** [comment]
I am not sure I understand. You can already set all the SWF Activities options (StartToStop, ScheduledToStart, ScheduledToStop, ...) in the plan.

Are you looking for something else?

**Comment by koxon** [comment]
Last time I checked the doc I didn't see those options. Will check again.
On the activity level too?

**Comment by koxon** [comment]
I am talking about the Workflow timeout options here. Not the activity options. 
I don't see how I can change those option when the workflow gets created.

We need this in order to prevent workflow timeout. So workflow can be queued in SWF and we can auto scale using the queue state.

Is it something you can look at ceache ?

**Comment by ceache** [comment]
I think I told you this before but you can set start_to_end_timeout,
scheduled_to_start_timeout and scheduled_to_end_timeout on each activity
(i.e. I just allow all the swf attributes).

Did you try setting your desired values there?

**Comment by koxon** [comment]
You mentioned:

You can already set all the SWF Activities options (StartToStop, ScheduledToStart, ScheduledToStop, ...) in the plan.

I am talking about Workflow options. Is that also possible ?

**Comment by koxon** [comment]
I added the Workflow timeout options in the plan, but they are not taken when the Decider create the workflow. Some parameters need to be added. @ceache any chance you can look at the workflow creation and use those new parameters to create it correctly ?
